name: cargo-test
on: [push]
jobs:
  check-bats-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-2019", "macos-11.0", "macos-10.15"]
    steps:
      - uses: actions/checkout@v2
      - run: cargo test
